version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AhmedMaged123321
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  account-service:
    build:
      context: ./account-service
    env_file:
      - ./account-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka

  user-service:
    build:
      context: ./user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka

  transaction-service:
    build:
      context: ./transaction-service
    env_file:
      - ./transaction-service/.env
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka
  
  bff-service:
    build:
      context: ./bff-service
    ports:
      - "8084:8084"
    depends_on:
      - account-service
      - user-service
      - transaction-service
      - logging-service
      - kafka
  
  logging-service:
    build:
      context: ./logging-service
    env_file:
      - ./logging-service/.env
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - postgres

volumes:
  pgdata:
