package com.microservice.user.service;

import io.github.cdimascio.dotenv.Dotenv;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class UserServiceApplication {


	public static void main(String[] args) {
		Dotenv dotenv = Dotenv.configure()
 				.ignoreIfMissing()
				.load();

		setIfNotNull("DB_PORT", dotenv.get("DB_PORT"));
		setIfNotNull("DB_NAME", dotenv.get("DB_NAME"));
		setIfNotNull("DB_USER", dotenv.get("DB_USER"));
		setIfNotNull("DB_PASSWORD", dotenv.get("DB_PASSWORD"));
		setIfNotNull("SERVER_PORT", dotenv.get("SERVER_PORT"));

		SpringApplication.run(UserServiceApplication.class, args);
	}

	private static void setIfNotNull(String key, String value) {
		if (value != null) {
			System.setProperty(key, value);
		} else {
			System.out.println("⚠️ Warning: environment variable " + key + " is not set.");
		}
	}

}
